version: "3"

networks:
  kafka_interaction:
    driver: bridge

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:latest
    container_name: zookeeper
    networks:
      - kafka_interaction
    ports:
      - "2181:2181"
    volumes:
      - "/mnt/c/Users/hp/Documents/kafka/zookeeper:/bitnami/zookeeper"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:latest
    container_name: kafka
    networks:
      - kafka_interaction
    ports:
      - "9094:9094"
    volumes:
      - "/mnt/c/Users/hp/Documents/kafka/kafka:/bitnami/kafka"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    depends_on:
      - zookeeper
  schema-registry:
    image: docker.io/bitnami/schema-registry:latest
    container_name: schema-registry
    networks:
      - kafka_interaction
    ports:
      - "8081:8081"
    volumes:
      - "/mnt/c/Users/hp/Documents/kafka/schema-registry:/bitnami"
    environment:
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
      - SCHEMA_REGISTRY_KAFKA_BROKERS=PLAINTEXT://kafka:9092
    depends_on:
      - kafka
      - zookeeper
